apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-qfhxxa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-qfhxxa
    app.kubernetes.io/part-of: jvm-build-suite-application-mfhi
  name: jvm-build-suite-component-qfhxxa
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: jvm-build-suite-component-qfhxxa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: jvm-build-suite-component-qfhxxa
    spec:
      containers:
      - image: quay.io/mbasti-test-org/jvm-build-cxhx-tenant/jvm-build-suite-application-mfhi/jvm-build-suite-component-qfhxxa@sha256:488d895d44e0b6e59ecb90cd200a2a8e1dff4161234360661014d0e85bc8a9ec
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
